#!/usr/bin/env python3
"""
cluster_serp.py — group live SERP output into search-intent clusters.

Stdlib only. This is a CONVENIENCE for Stage 1: if it errors, cluster inline
instead. It does NOT invent data — it only organizes what was scraped.

Input (stdin or file arg): JSON, either a single SERP object or a list of them,
each shaped roughly like the Bright Data search_engine result:

{
  "query": "best crm for small business",
  "organic": [{"title": "...", "url": "...", "snippet": "..."}, ...],
  "people_also_ask": ["how much does a crm cost?", ...],
  "related_searches": ["free crm for small business", ...]
}

Output: a Markdown report (clusters -> queries) to stdout.

Usage:
  python3 cluster_serp.py < serp.json
  python3 cluster_serp.py serp.json
"""

import json
import sys

# Intent buckets keyed by signal words found in a query/term.
INTENT_RULES = [
    ("Transactional", ["buy", "price", "pricing", "cost", "deal", "discount",
                        "coupon", "subscribe", "sign up", "free trial", "demo",
                        "quote", "order", "hire"]),
    ("Commercial investigation", ["best", "top", "vs", "versus", "compare",
                                  "comparison", "alternative", "alternatives",
                                  "review", "reviews", "cheapest", "for small",
                                  "for startups", "software", "tool", "tools",
                                  "platform", "service"]),
    ("Navigational", ["login", "log in", "sign in", "download", "app",
                      "official", "website", "account", "dashboard", "portal"]),
    ("Informational", ["how", "what", "why", "when", "guide", "tutorial",
                       "examples", "tips", "ideas", "meaning", "definition",
                       "explained", "vs.", "checklist", "template"]),
]
DEFAULT_INTENT = "Informational"


def classify(term: str) -> str:
    t = (term or "").lower()
    for intent, signals in INTENT_RULES:
        for s in signals:
            if s in t:
                return intent
    # questions default to informational
    if t.endswith("?") or t.split()[:1] and t.split()[0] in (
            "how", "what", "why", "when", "where", "who", "which"):
        return "Informational"
    return DEFAULT_INTENT


def load_input():
    raw = open(sys.argv[1]).read() if len(sys.argv) > 1 else sys.stdin.read()
    if not raw.strip():
        sys.exit("No input. Pipe SERP JSON in or pass a file path.")
    data = json.loads(raw)
    return data if isinstance(data, list) else [data]


def collect_terms(serps):
    """Return list of (term, source, ranking_urls). Dedup case-insensitively."""
    seen = {}
    for serp in serps:
        q = serp.get("query", "").strip()
        urls = [o.get("url", "") for o in serp.get("organic", []) if o.get("url")]
        if q:
            seen.setdefault(q.lower(), (q, "seed query", urls[:3]))
        for paa in serp.get("people_also_ask", []) or []:
            term = paa.get("question", paa) if isinstance(paa, dict) else paa
            term = str(term).strip()
            if term:
                seen.setdefault(term.lower(), (term, "People Also Ask", []))
        for rel in serp.get("related_searches", []) or []:
            term = str(rel).strip()
            if term:
                seen.setdefault(term.lower(), (term, "Related search", []))
    return list(seen.values())


def main():
    serps = load_input()
    terms = collect_terms(serps)

    clusters = {}
    for term, source, urls in terms:
        clusters.setdefault(classify(term), []).append((term, source, urls))

    order = ["Informational", "Commercial investigation",
             "Transactional", "Navigational"]
    out = ["# Stage 1 — Intent Clusters (from live SERP)\n"]
    out.append(f"_Source queries scraped: "
               f"{', '.join(s.get('query','?') for s in serps)}_\n")
    for intent in order:
        rows = clusters.get(intent)
        if not rows:
            continue
        out.append(f"## {intent}  ({len(rows)} queries)\n")
        out.append("| Query / question | Found via | Example ranking URLs |")
        out.append("|---|---|---|")
        for term, source, urls in sorted(rows, key=lambda r: r[0].lower()):
            u = "<br>".join(urls) if urls else "—"
            out.append(f"| {term} | {source} | {u} |")
        out.append("")
    out.append("> Generated by cluster_serp.py from live scraped SERP data only.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
